Repository Automattic/zoninator, pull requests merged in 2024-08, with the labels that each got.

#93 UI: Fix typo and clarify Add Zone description
  zoninator.php
Labels: Type: bug

#82 Send empty set when search yields no results
  zoninator.php
Labels: Type: bug

#69 Increase autocomplete timeout
  js/zoninator.js
Labels: Type: bug

#90 Fix bytes
  .editorconfig
  .gitattributes
  .github/workflows/cs-lint.yml
  .gitignore
  LICENSE
  README.md
  bin/install-wp-tests.sh
  composer.json
  css/jquery-ui/smoothness/jquery-ui-zoninator.css
  functions.php
  includes/class-zoninator-api-controller.php
  includes/class-zoninator-api-schema-converter.php
  includes/class-zoninator-api.php
  js/zoninator.js
  lib/zoninator_rest/controller/class-zoninator-rest-controller-crud.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-model.php
  lib/zoninator_rest/interfaces/data/class-zoninator-rest-interfaces-data-store.php
  lib/zoninator_rest/model/class-zoninator-rest-model-validationdata.php
  package.json
  phpunit.xml.dist
  readme.txt
  tests/bootstrap.php
  tests/unit/class-zoninator-api-controller-test.php
  widget.zone-posts.php
  zoninator.php
Labels: Type: maintenance, Status: awaiting feedback

#95 CI: Use valid runs-on value, and fix some issues
  .github/workflows/integrations.yml
  composer.json
Labels: Type: maintenance

#96 CI: Update action versions
  .github/workflows/cs-lint.yml
  .github/workflows/integrations.yml
Labels: Type: maintenance

#98 Increase min WP and PHP versions
  .github/workflows/cs-lint.yml
  .github/workflows/integrations.yml
  .phpcs.xml.dist
  composer.json
  readme.txt
  tests/unit/class-zoninator-api-controller-test.php
Labels: Type: maintenance

#99 Docs: Various improvements
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  CHANGELOG.md
  README.md
  readme.txt
Labels: Type: maintenance

#101 Add auto-deploy for WordPress.org plugin repo
  .distignore
  .gitattributes
  .github/workflows/deploy.yml
  .gitignore
Labels: Type: maintenance

#102 Release version 0.10.0
  .distignore
  .editorconfig
  .gitattributes
  .github/workflows/cs-lint.yml
  .github/workflows/deploy.yml
  .github/workflows/integrations.yml
  .gitignore
  .phpcs.xml.dist
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  CHANGELOG.md
  LICENSE
  README.md
  bin/install-wp-tests.sh
  composer.json
  css/jquery-ui/smoothness/jquery-ui-zoninator.css
  functions.php
  includes/class-zoninator-api-controller.php
  includes/class-zoninator-api-schema-converter.php
  includes/class-zoninator-api.php
  js/zoninator.js
  lib/zoninator_rest/class-zoninator-rest-controller.php
  lib/zoninator_rest/class-zoninator-rest-environment.php
  lib/zoninator_rest/class-zoninator-rest-expect.php
  lib/zoninator_rest/class-zoninator-rest-model.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-crud.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-model.php
  lib/zoninator_rest/interfaces/data/class-zoninator-rest-interfaces-data-store.php
  lib/zoninator_rest/model/class-zoninator-rest-model-settings.php
  lib/zoninator_rest/model/class-zoninator-rest-model-validationdata.php
  lib/zoninator_rest/model/declaration/class-zoninator-rest-model-declaration-settings.php
  package-lock.json
  package.json
  phpunit.xml.dist
  readme.txt
  tests/bootstrap.php
  tests/unit/class-zoninator-api-controller-test.php
  widget.zone-posts.php
  zoninator.php
Labels: Type: maintenance

#103 Update develop with release branch updates
  CHANGELOG.md
  README.md
  bin/install-wp-tests.sh
  package.json
  zoninator.php
Labels: Type: maintenance

#106 Deploy: Don't include .git/ directory
  .distignore
Labels: Type: maintenance

#107 Add and apply Rector
  composer.json
  functions.php
  includes/class-zoninator-api-controller.php
  includes/class-zoninator-api-filter-search.php
  includes/class-zoninator-api-schema-converter.php
  includes/class-zoninator-api.php
  lib/zoninator_rest/class-zoninator-rest-bootstrap.php
  lib/zoninator_rest/class-zoninator-rest-classloader.php
  lib/zoninator_rest/class-zoninator-rest-controller.php
  lib/zoninator_rest/class-zoninator-rest-environment.php
  lib/zoninator_rest/class-zoninator-rest-expect.php
  lib/zoninator_rest/class-zoninator-rest-model.php
  lib/zoninator_rest/class-zoninator-rest-type.php
  lib/zoninator_rest/controller/bundle/class-zoninator-rest-controller-bundle-builder.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-action.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-bundle.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-crud.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-extension.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-model.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-route.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-settings.php
  lib/zoninator_rest/data/class-zoninator-rest-data-mapper.php
  lib/zoninator_rest/data/class-zoninator-rest-data-serializer.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-abstract.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-builder.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-customposttype.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-nil.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-option.php
  lib/zoninator_rest/field/class-zoninator-rest-field-declaration.php
  lib/zoninator_rest/field/declaration/class-zoninator-rest-field-declaration-builder.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-builder.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-classloader.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-controller.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-model.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-registrable.php
  lib/zoninator_rest/interfaces/class-zoninator-rest-interfaces-type.php
  lib/zoninator_rest/interfaces/data/class-zoninator-rest-interfaces-data-store.php
  lib/zoninator_rest/interfaces/model/class-zoninator-rest-interfaces-model-collection.php
  lib/zoninator_rest/interfaces/model/class-zoninator-rest-interfaces-model-declaration.php
  lib/zoninator_rest/model/class-zoninator-rest-model-declaration.php
  lib/zoninator_rest/model/class-zoninator-rest-model-definition.php
  lib/zoninator_rest/model/class-zoninator-rest-model-settings.php
  lib/zoninator_rest/model/class-zoninator-rest-model-validationdata.php
  lib/zoninator_rest/model/declaration/class-zoninator-rest-model-declaration-settings.php
  lib/zoninator_rest/model/definition/class-zoninator-rest-model-definition-builder.php
  lib/zoninator_rest/type/class-zoninator-rest-type-boolean.php
  lib/zoninator_rest/type/class-zoninator-rest-type-integer.php
  lib/zoninator_rest/type/class-zoninator-rest-type-nullable.php
  lib/zoninator_rest/type/class-zoninator-rest-type-number.php
  lib/zoninator_rest/type/class-zoninator-rest-type-registry.php
  lib/zoninator_rest/type/class-zoninator-rest-type-string.php
  lib/zoninator_rest/type/class-zoninator-rest-type-typedarray.php
  rector.php
  tests/bootstrap.php
  tests/unit/class-zoninator-api-controller-test.php
  widget.zone-posts.php
  zoninator.php
Labels: Type: maintenance

#109 Release 0.10.1
  .distignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  zoninator.php
Labels: Type: bug

#112 CS: Fix or ignore coding standards issues
  .github/workflows/cs-lint.yml
  .phpcs.xml.dist
  functions.php
  includes/class-zoninator-api-controller.php
  includes/class-zoninator-api-filter-search.php
  includes/class-zoninator-api-schema-converter.php
  lib/zoninator_rest/class-zoninator-rest-classloader.php
  lib/zoninator_rest/class-zoninator-rest-environment.php
  lib/zoninator_rest/class-zoninator-rest-expect.php
  lib/zoninator_rest/class-zoninator-rest-model.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-action.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-bundle.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-crud.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-model.php
  lib/zoninator_rest/controller/class-zoninator-rest-controller-settings.php
  lib/zoninator_rest/data/store/class-zoninator-rest-data-store-customposttype.php
  lib/zoninator_rest/field/class-zoninator-rest-field-declaration.php
  lib/zoninator_rest/field/declaration/class-zoninator-rest-field-declaration-builder.php
  lib/zoninator_rest/interfaces/data/class-zoninator-rest-interfaces-data-store.php
  lib/zoninator_rest/model/class-zoninator-rest-model-declaration.php
  lib/zoninator_rest/type/class-zoninator-rest-type-registry.php
  widget.zone-posts.php
  zoninator.php
Labels: Type: maintenance
